version: "3.0"
services:
 cms:
    build: ./
    volumes:
      - ../code/cms:/app/code
      - ../node_modules/:/node_modules/
    ports:
      - "4001:4000" 
      - "8111:80" 
    tty : true
    container_name:
      nodejs-cms
